// <auto-generated />
using System;
using CovidData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CovidData.Migrations
{
    [DbContext(typeof(CovidDataContext))]
    [Migration("20220515182731_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("CovidData.Models.CovidCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumSequences")
                        .HasColumnType("int");

                    b.Property<int>("NumSequencesTotal")
                        .HasColumnType("int");

                    b.Property<double>("PercSequences")
                        .HasColumnType("double");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CovidCases");
                });
#pragma warning restore 612, 618
        }
    }
}
